name: TotoruOps
description: Blogging about stuffs
meta_description: "TotoruOps - Tech, Leadership, Education and Fathership"

# markdown: kramdown
# highlighter: rouge
# logo: false
# paginate: 15
baseurl: ""
domain_name: "https://totoruops.com"
# google_analytics: "UA-XXXXXXXX-X"

# Details for the RSS feed generator
# url: ""
# author: "Wagner Hitomi"

# Disqus config
# disqus-shortname: ""

theme: jekyll-theme-slate
# plugins: [jekyll-paginate]
